Forum-Project/ForumTemplate/Models/Post.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ForumTemplate.Models
{
    public class Post
    {
        // Properties
        public Guid PostId { get; set; }
        public string Title { get; set; } = null!;
        public string Content { get; set; } = null!;
    //    public int LikePost { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }

        // Foreign key
        public Guid UserId { get; set; }
        public User User { get; set; } = null!;
        
        public virtual ICollection<Like> Likes { get; set; } = new List<Like>();
        public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
        public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();
        public bool IsDelete { get; set; }
        public Post()
        {
            // Private parameterless constructor for EF Core
            // to enable entity creation via reflection
        }
        private Post(
            string title,
            string content,
            Guid userId
            )
        {
            PostId = Guid.NewGuid();
            Title = title;
            Content = content;
            UserId = userId;
            CreatedAt = DateTime.UtcNow;
        }

        // Methods
        public static Post CreatePost(string title, string content, Guid userId)
        {
            return new Post(title, content, userId);
        }
        public Post Update(Post post)
        {
            this.Title = post.Title;
            this.Content = post.Content;
            this.UpdatedAt = DateTime.UtcNow;

            return this;
        }
    }
}

Forum-Project/ForumTemplate/Models/ViewModels/PostViewModel.cs
using ForumTemplate.DTOs.PostDTOs;

namespace ForumTemplate.Models.ViewModels
{
    public class PostViewModel : PostRequest
    {
        
    }
}

Forum-Project/ForumTemplate/Controllers/CommentsController.cs
using ForumTemplate.Authorization;
using ForumTemplate.DTOs.CommentDTOs;
using ForumTemplate.Exceptions;
using ForumTemplate.Mappers;
using ForumTemplate.Models;
using ForumTemplate.Models.ViewModels;
using ForumTemplate.Services.CommentService;
using ForumTemplate.Services.PostService;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;

namespace ForumTemplate.Controllers
{
    public class CommentsController : Controller
    {
        private readonly IPostService postService;
        private readonly ICommentService commentService;
        private readonly IPostMapper postMapper;
        private readonly ICommentMapper commentMapper;
        private readonly IAuthManager authManager;
        public CommentsController(IPostService postService, IPostMapper postMapper, IAuthManager authManager, ICommentService cpmmentService, ICommentMapper commentMapper)
        {
            this.postService = postService;
            this.postMapper = postMapper;
            this.authManager = authManager;
            this.commentService = cpmmentService;
            this.commentMapper = commentMapper;
        }

        [HttpGet]
        public IActionResult Create(Guid id)
        {
            if (this.authManager.CurrentUser == null)
            {
                return this.RedirectToAction("Login", "Auth");
            }

            var commentViewModel = new CommentViewModel
            {
                Id = id
            };

            return View(commentViewModel);
        }

        [HttpPost]
        public IActionResult Create([FromRoute]Guid id, CommentViewModel commentViewModel)
        {
            if (this.authManager.CurrentUser == null)
            {
                return this.RedirectToAction("Login", "Auth");
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(commentViewModel);
            }

            var viewModel = new CommentViewModel
            {
                Id = id
            };

            try
            {
                var user = this.authManager.CurrentUser;
                var comment = new CommentRequest
                {
                    Content = commentViewModel.Content,
                    UserId = user.UserId,
                    PostId = commentViewModel.Id
                };
                var createdComment = this.commentService.Create(user, comment);

                return RedirectToAction("Details", "Posts", new { id = comment.PostId });
                //return RedirectToAction("Details", "Posts");
            }
            catch (EntityBannedException e)
            {
                this.Response.StatusCode = StatusCodes.Status403Forbidden;
                this.ViewData["ErrorMessage"] = e.Message;

                return this.View("Error");
            }
            catch (ValidationException e)
            {
                this.Response.StatusCode = StatusCodes.Status404NotFound;
                this.ViewData["ErrorMessage"] = e.Message;

                return this.View("Error");
            }
            catch (EntityNotFoundException e)
            {
                this.Response.StatusCode = StatusCodes.Status404NotFound;
                this.ViewData["ErrorMessage"] = e.Message;

                return this.View("Error");
            }
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            if (this.authManager.CurrentUser == null)
            {
                return this.RedirectToAction("Login", "Auth");
            }

            var comment = this.commentService.GetById(id);
            var commentViewModel = new CommentViewModel
            {
                Id = comment.PostId
            };

            return View(commentViewModel);
        }

        [HttpPost]
        public IActionResult Edit(CommentViewModel commentViewModel)
        {
            try
            {
                var user = this.authManager.CurrentUser;
                var commentResponse = this.commentService.GetById(commentViewModel.Id);
                var commentRequest = this.commentMapper.MapToCommentRequest(commentResponse);
                commentRequest.Content = commentViewModel.Content;
                var comment = this.commentService.Update(user,commentViewModel.Id, commentRequest);

                return RedirectToAction("Details", "Posts", new { id = comment.PostId });
            }
            catch (ValidationException e)
            {
                this.Response.StatusCode = StatusCodes.Status404NotFound;
                this.ViewData["ErrorMessage"] = e.Message;

                return this.View("Error");
            }
            catch (EntityNotFoundException e)
            {
                this.Response.StatusCode = StatusCodes.Status404NotFound;
                this.ViewData["ErrorMessage"] = e.Message;

                return this.View("Error");
            }
        }
    }
}

Forum-Project/ForumTemplate/Controllers/LikesController.cs
using ForumTemplate.Authorization;
using ForumTemplate.Services.LikeService;
using Microsoft.AspNetCore.Mvc;

namespace ForumTemplate.Controllers
{
    public class LikesController : Controller
    {
        private readonly ILikeService likeService;
        private readonly IAuthManager authManager;

        public LikesController(IAuthManager authManager, ILikeService likeService)
        {

            this.authManager = authManager;
            this.likeService = likeService;
        }

        [HttpPost]
        public IActionResult Like(Guid postId)
        {
            // Проверка дали потребителят е логнат
            if (this.authManager.CurrentUser == null)
            {
                return this.RedirectToAction("Login", "Auth");
            }

            // Извикване на сервизния метод за лайкване на поста
            var user = this.authManager.CurrentUser;
            likeService.LikeUnlike(user,postId);

            // Пренасочване към детайлите на поста
            return RedirectToAction("Details", "Posts", new { id = postId });
        }
    }
}

Forum-Project/ForumTemplate/Controllers/PostsController.cs
using ForumTemplate.Authorization;
using ForumTemplate.Exceptions;
using ForumTemplate.Mappers;
using ForumTemplate.Models;
using ForumTemplate.Models.ViewModels;
using ForumTemplate.Services.PostService;
using ForumTemplate.Services.UserService;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using System.Text.RegularExpressions;

namespace ForumTemplate.Controllers
{
    public class PostsController : Controller
    {
        private readonly IPostService postService;
        private readonly IPostMapper postMapper;
        private readonly IAuthManager authManager;

        public PostsController(IPostService postService, IPostMapper postMapper, IAuthManager authManager)
        {
            this.postService = postService;
            this.postMapper = postMapper;
            this.authManager = authManager;
        }

        [HttpGet]
        public IActionResult Index([FromQuery] PostQueryParameters postQueryParameters)
        {
            var posts = this.postService.SearchBy(postQueryParameters);

            return this.View(posts);
        }

        [HttpGet]
        public IActionResult Details(Guid id)
        {
            try
            {
                var post = this.postService.GetByPostId(id);

                return this.View(post);
            }
            catch (ValidationException e)
            {
                this.Response.StatusCode = StatusCodes.Status404NotFound;
                this.ViewData["ErrorMessage"] = e.Message;

                return this.View("Error");
            }
        }

        [HttpGet]
        public IActionResult Create()
        {
            if (this.authManager.CurrentUser == null)
            {
                return this.RedirectToAction("Login", "Auth");
            }

            var postViewModel = new PostViewModel();
            return this.View(postViewModel);
        }

        [HttpPost]
        public IActionResult Create(PostViewModel postViewModel)
        {

            try
            {
                if (!this.ModelState.IsValid)
                {
                    return this.View(postViewModel);
                }

                if (this.authManager.CurrentUser == null)
                {
                    return this.RedirectToAction("Login", "Auth");
                }

                var user = this.authManager.CurrentUser;
                var post = postMapper.MapToPostRequest(postViewModel, user.UserId);
                var createdPost = postService.Create(user, post);

                //var tagRegex = new Regex(@"(?<=#|\s|^)(\w+)");
                //var matches = tagRegex.Matches(post.Content);

                //// Създайте колекция за съхранение на таговете
                //var tags = new List<string>();

                //// Извлечете само текста на таговете и го добавете към колекцията
                //foreach (Match match in matches)
                //{
                //    var tag = match.Groups[1].Value;
                //    tags.Add(tag);
                //}

                return RedirectToAction("Details", "Posts", new { id = createdPost.Id });

            }
            catch (EntityBannedException e)
            {
                this.Response.StatusCode = StatusCodes.Status403Forbidden;
                this.ViewData["ErrorMessage"] = e.Message;

                return this.View("Error");
            }
        }

        [HttpGet]
        public IActionResult Edit([FromRoute] Guid id)
        {
            if (this.authManager.CurrentUser == null)
            {
                return this.RedirectToAction(actionName: "Login", controllerName: "Auth");
            }
      
            try
            {
                var post = postService.GetByPostId(id);

                if (post.UserId != this.authManager.CurrentUser.UserId && !this.authManager.CurrentUser.IsAdmin)
                {
                    this.Response.StatusCode = StatusCodes.Status403Forbidden;
                    this.ViewData["ErrorMessage"] = $"You cannot edit the post since your are not the author.";

                    return this.View("Error");
                }

                var postViewModel = postMapper.MapToPostViewModel(post);

                return View(postViewModel);

            }
            catch (ValidationException e)
            {
                this.Response.StatusCode = StatusCodes.Status404NotFound;
                this.ViewData["ErrorMessage"] = e.Message;

                return View("Error");
            }
        }

        [HttpPost]
        public IActionResult Edit([FromRoute] Guid id, PostViewModel postViewModel)
        {
            try
            {
                if (!this.ModelState.IsValid)
                {
                    return this.View(postViewModel);
                }

                var user = this.authManager.CurrentUser;
                var post = postMapper.MapToPostRequest(postViewModel, user.UserId);
                var updatedPost = postService.Update(user, id, post);
                var updatedPostViewModel = postMapper.MapToPostViewModel(updatedPost);

                return RedirectToAction("Details", "Posts", new { id = updatedPost.Id });

            }
            catch (ValidationException e)
            {
                this.Response.StatusCode = StatusCodes.Status404NotFound;
                this.ViewData["ErrorMessage"] = e.Message;

                return View("Error");
            }
        }

        [HttpGet]
        public IActionResult Delete([FromRoute] Guid id)
        {
            if (this.authManager.CurrentUser == null)
            {
                return this.RedirectToAction(actionName: "Login", controllerName: "Auth");
            }

            try
            {
                var post = postService.GetByPostId(id);

                if (post.UserId != this.authManager.CurrentUser.UserId && !this.authManager.CurrentUser.IsAdmin)
                {
                    this.Response.StatusCode = StatusCodes.Status403Forbidden;
                    this.ViewData["ErrorMessage"] = $"You cannot delete the post since your are not the author.";

                    return this.View("Error");
                }

                var postViewModel = postMapper.MapToPostViewModel(post);

                return View(postViewModel);

            }
            catch (ValidationException e)
            {
                this.Response.StatusCode = StatusCodes.Status404NotFound;
                this.ViewData["ErrorMessage"] = e.Message;

                return View("Error");
            }
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed([FromRoute] Guid id)
        {
            var user = this.authManager.CurrentUser;
            _ = postService.Delete(user, id);

            return RedirectToAction("Index", "Posts");
        }
    }
}

Forum-Project/ForumTemplate/Views/Posts/Create.cshtml
@{
    this.ViewData["Title"] = "Create";
}
@model PostViewModel

<h2>Create a new post</h2>
<form asp-controller="Posts" asp-action="Create" method="post">
    <div>
        <label asp-for="Title" class="form-label"></label>
        <br />
        <input asp-for="Title" type="text" class="form-input" />
        <span asp-validation-for="Title" class="form-error"></span>
    </div>
    <div>
        <label asp-for="Content" class="form-label"></label>
        <br />
        <input asp-for="Content" type="text" class="form-input" />
        <span asp-validation-for="Content" class="form-error"></span>
    </div>
    <input type="submit" value="Create" class="btn-primary" />
    <a asp-controller="Posts" asp-action="Index" class="nav">Back</a>
</form>

Forum-Project/ForumTemplate/Views/Posts/Delete.cshtml
@{
    this.ViewData["Title"] = "Delete";
}
<h2>Delete <b>@this.Model.Title</b>?</h2>

<form asp-controller="Posts" asp-action="Delete" method="post">
    <input type="submit" value="Delete" class="btn-danger" />
</form>

<a asp-controller="Posts" asp-action="Index" class="nav">Back</a>

Forum-Project/ForumTemplate/Views/Posts/Details.cshtml
@{
    this.ViewData["Title"] = "Details";
}
@model Post

<h2>
    @this.Model.Content
</h2>
<h3>
    From: @this.Model.User.Username
</h3>

@*Форма за like/unlike *@

@if (authManager.CurrentUser is not null)
{
    <form asp-controller="Likes" asp-action="Like" method="post">
        <input type="hidden" name="postId" value="@Model.PostId" />
        <button type="submit" class="btn btn-link like-button" style="color: @(Model.Likes.Any(l => l.UserId == authManager.CurrentUser?.UserId && l.Liked) ? "blue" : (Model.Likes.Any(l => l.UserId == authManager.CurrentUser?.UserId && !l.Liked) ?"black" : "black"));">
            <i class="fa-thumbs-up-icon fas @(Model.Likes.Any(l => l.UserId == authManager.CurrentUser?.UserId && l.Liked) ? "fa-thumbs-up" : "fa-thumbs-up")"></i>
        </button>
        <span>@Model.Likes.Count(l => l.Liked)</span>
    </form>
}
@*Само ако си логнат и си автор на поста или админ имаш опции за edit/delete*@
@if (authManager.CurrentUser is not null && (authManager.CurrentUser.UserId == this.Model.UserId || authManager.CurrentUser.IsAdmin))
{
    <div>
        <a asp-controller="Posts" asp-action="Edit" asp-route-id="@this.Model.PostId" class="btn btn-primary">Edit Post</a>
        <a asp-controller="Posts" asp-action="Delete" asp-route-id="@this.Model.PostId" class="btn btn-danger">Delete Post</a>
    </div>
}


<h4> <a asp-controller="Comments" asp-action="Create" asp-route-id="@Model.PostId" class="btn btn-primary">Add a comment</a></h4>

<h4>Comments <br></h4>

@if (this.Model.Comments.Count == 0)
{
    <p>
        <i>No comments</i>
    </p>
}
else
{
    <ul>
        @foreach (var comment in this.Model.Comments.OrderByDescending(x => x.CreatedAt))
        {
            <li class="margin12">
                Comment from @comment.User.Username <br>
                Published at: @comment.CreatedAt
                @if (authManager.CurrentUser is not null && (authManager.CurrentUser.UserId == this.Model.UserId || authManager.CurrentUser.IsAdmin || authManager.CurrentUser.UserId == comment.UserId))
                {
                 
                        <a asp-controller="Comments" asp-action="Edit" asp-route-id="@comment.CommentId" class="btn btn-warning">Edit</a>
               
                }
                <br>
                <p>@comment.Content</p>
                <hr>
            </li>
        }
    </ul>
}

@if (authManager.CurrentUser is null)
{
    <a asp-controller="Home" asp-action="Index" class="nav">Go back</a>
}

@if(authManager.CurrentUser is not null)
{
    <a asp-controller="Posts" asp-action="Index" class="nav">See all posts</a>
}

Forum-Project/ForumTemplate/Views/Posts/Edit.cshtml
@{
	this.ViewData["Title"] = "Edit";
}
@model PostViewModel

<h2>@this.Model.Title</h2>
<form asp-controller="Posts" asp-action="Edit" method="post">
	<div>
		<label asp-for="Title" class="form-label"></label>
		<br />
		<input asp-for="Title" type="text" class="form-input" />
		<span asp-validation-for="Title" class="form-error"></span>
	</div>
	<div>
		<label asp-for="Content" class="form-label"></label>
		<br />
		<input asp-for="Content" type="text" class="form-input" />
		<span asp-validation-for="Content" class="form-error"></span>
	</div>
	<input type="submit" value="Save" class="btn-primary" />
	<a asp-controller="Posts" asp-action="Index" class="nav">Back</a>
</form>

Forum-Project/ForumTemplate/Views/Posts/Index.cshtml
@{
    this.ViewData["Title"] = "Posts";
}
@model PaginatedList<Post>

<h2>Posts</h2>
@if (authManager.CurrentUser is not null)
{
    <p>
        <a asp-controller="Posts" asp-action="Create" class="btn btn-primary">Create a new post</a>
    </p>
}

<p>Find a post</p>
<form asp-controller="Posts" asp-action="Index" method="get">
    <input type="text" name="Title" />
    <input type="submit" value="Search" class="btn btn-primary" />
</form>


<div class="table">
    <div class="header">
        <div class="header-cell">Title</div>
    </div>

    @{
        foreach (var post in this.Model)
        {
            <a class="row clickable-row" href="@Url.Action("Details", "Posts", new { id = post.PostId })">
                <div class="cell">@post.Title</div>
            </a>
        }
    }
</div>


@*Pagination*@
@{
    string prevButtonState = this.Model.HasPrevPage ? "" : "disabled";
    string nextButtonState = this.Model.HasNextPage ? "" : "disabled";
}

<a asp-controller="Posts" asp-action="Index" asp-route-PageNumber="@(this.Model.PageNumber - 1)" class="btn btn-link @prevButtonState">Prev</a>

@{
    int currentPageNumber = this.Model.PageNumber;
    int totalPages = this.Model.TotalPages;
    int pageRange = 3; // Брой страници, които да се показват преди и след текущата страница
    int startPage = Math.Max(1, currentPageNumber - pageRange);
    int endPage = Math.Min(totalPages, currentPageNumber + pageRange);

    if (startPage > 1)
    {
        <span><a asp-controller="Posts" asp-action="Index" asp-route-PageNumber="1">1</a></span>
        if (startPage > 2)
        {
            <span>...</span>
        }
    }

    for (int i = startPage; i <= endPage; i++)
    {
        if (i == currentPageNumber)
        {
            <span>@i</span>
        }
        else
        {
            <span><a asp-controller="Posts" asp-action="Index" asp-route-PageNumber="@i">@i</a></span>
        }
    }

    if (endPage < totalPages)
    {
        if (endPage < totalPages - 1)
        {
            <span>...</span>
        }
        <span><a asp-controller="Posts" asp-action="Index" asp-route-PageNumber="@totalPages">@totalPages</a></span>
    }
}

<a asp-controller="Posts" asp-action="Index" asp-route-PageNumber="@(this.Model.PageNumber + 1)" class="btn btn-link @nextButtonState">Next</a>